### ISSUE TITLE
Tor Weather is sending an outdated link

### ISSUE THREAD

**Issue by li5lo** [thingless/torweather#4]
The link to the relay details Tor Weather is sending in the email is an `​https://atlas.torproject.org/#` link.
But atlas is deprecated and permanently redirects to `https://metrics.torproject.org/rs.html#`

https://gitlab.torproject.org/legacy/trac/-/issues/25286

**Comment by za3k** [comment]
https://github.com/thingless/torweather/commit/8fe26e8fb9db3c14399458983bf9bb1092d6df42
